### ISSUE TITLE
Question related to Azure deployment process

### ISSUE THREAD

**Issue by pgavrailov** [OfficeDev/microsoft-teams-list-search-app#1]
Very good article, easy to follow, however I have a dump question. How does Azure know what exactly has to be deployed? I mean as far as I understood it, all I did following along was to create few APP IDs and to attach them to Resource Group in Azure. I have no clue how and why after I clicked deploy Azure decided to add all those services , apps etc to the resource group ?

**Comment by aosolis** [comment]
@pgavrailov The Azure Resource Manager (ARM) template [here](https://github.com/OfficeDev/microsoft-teams-list-search-app/blob/master/Deployment/azuredeploy.json) specifies the resources that are created and the links between them. This [page](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview#template-deployment) has an overview of ARM templates, how they work, and how to create your own. There's also a library of [quickstart templates](https://azure.microsoft.com/en-us/resources/templates/) that you can check out for examples, or customize for your own scenario.

**Comment by aosolis** [comment]
The "Deploy to Azure" button is an image link takes you to the Azure Portal function to create a deployment based on a given ARM template, and it points to the ARM template that I linked to above. 

This is the link in this project's wiki:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-list-search-app%2Fmaster%2FDeployment%2Fazuredeploy.json
