### ISSUE TITLE
Unable to get nformation about the given Sharepoint List

### ISSUE THREAD

**Issue by MikedeVV** [OfficeDev/microsoft-teams-list-search-app#11]
Hi Team,

I keep given this error "Unable to get nformation about the given Sharepoint List" once I tried to connect the sharepoint list. Any idea how to solve it?
![SharedScreenshot](https://user-images.githubusercontent.com/51783432/85375100-1b5a8500-b536-11ea-9414-ad5fc6ba5c9a.jpg)

**Comment by Srivatsan0102** [comment]
Hello,

Please double check first if the URL you've given for the SharePoint list is correct. It should be of the format:

https://XXXXXXXX.sharepoint.com/sites/<<SharePointSiteName>>/Lists/<<ListName>>/AllItems.aspx

If this does not work, double check if the Sharepoint site you are using is in the same tenant as the one where you had deployed your resources. You will not be able to get the sharepoint list information if they are in separate tenants.

**Comment by dborchers-gc** [comment]
I also got those error but my URL is correct

https://*****.sharepoint.com/sites/0900_IT/Lists/ApplikationsStamm/AllItems.aspx

Are there any kind of logs where i can search for the reason? My users are Site Collection Admins, so everything should work
